config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  get "tasks", to: "tasks#index"
  
  resources :categories do
    resources :tasks, except: :index
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :user
    has_many :tasks, dependent: :destroy

    validates :name, presence: true, uniqueness: { scope: :user_id, case_sensitive: false, message: "are already exist" }
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :category

    validates :title, presence: true, uniqueness: { scope: :category_id, case_sensitive: false, message: "are already exist" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, dependent: :destroy
  has_many :tasks, through: :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    private
        def after_sign_out_path_for(resource)
            new_user_session_path
        end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories
  def index
    @categories = current_user.categories
  end

  # GET /categories/1
  def show
  end

  # GET /categories/new
  def new
    @category = current_user.categories.build
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = current_user.categories.build(category_params)

    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = current_user.categories.find_by_id(params[:id])
      if @category.nil?
        redirect_to categories_url, notice: "No category id #{params[:id]} found"
      end
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_action :authenticate_user!


  def index
    redirect_to categories_url if user_signed_in?
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_category, except: %i[ index ]
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks
  def index
    @tasks = current_user.tasks
    @due = @tasks.where(["date = ? AND completed = ?", Date.current, false])
  end

  # GET /categories/1/tasks/1
  def show
  end 

  # GET /categories/1/tasks/new
  def new
   @task = @category.tasks.build
  end

  # GET /categories/1/tasks/1/edit
  def edit
  end

  # POST /categories/1
  def create
    @task = @category.tasks.build(task_params)

    if @task.save
      redirect_to @category, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @task.update(task_params)
      redirect_to @category, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    @task.destroy
    redirect_to @category, notice: 'Task was successfully destroyed.'
  end

  private
    def set_category
      @category = current_user.categories.find_by_id(params[:category_id])
      if @category.nil?
        redirect_to category_url
      end
    end

    def set_task
      @task = @category.tasks.find_by_id(params[:id])
      if @task.nil?
        redirect_to category_url(@category), notice: "No task id #{params[:id]} found" 
      end
    end

    def task_params
      params.require(:task).permit(:title, :notes, :date, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field  mb-3">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>
  
  <br/>

  <div class="actions center">
    <%= form.submit class:"btn btn-update" %>
    <%= link_to 'Cancel', categories_path, class:"btn btn-cancel" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="card">
    <div class="card-body margin">
        <h1 class="center">Edit Category</h1>
        <br/>
        <%= render 'form', category: @category %>
        <br/>
    </div>
</div>

app/views/categories/index.html.erb
<div class="row">
  <% @categories.each do |category| %>
    <div class="col-sm-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= category.name %></h5>
          <p class="card-text"><%= category.tasks.count %> Tasks</p>
          <p class="card-text">Created <%= time_ago_in_words(category.created_at) %> ago</p>
          <div class="rud">
            <i class="show-icon bi-eye-fill"></i>
            <%= link_to 'Show', category, class:"show-icon" %>

            <i class="edit-icon bi-pencil-square"></i>
            <%= link_to 'Edit', edit_category_path(category), class:"edit-icon" %>

            <i class="delete-icon bi-trash-fill"></i>
            <%= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' }, class:"delete-icon" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/categories/new.html.erb
<div class="card">
    <div class="card-body margin">   
        <h1 class="center">New Category</h1>
        <br/>
        <%= render 'form', category: @category %>
        <br/>
    </div>
</div>

app/views/categories/show.html.erb
<div class="row">
  <div class="col-sm-13">
    <div class="card">
      <div class="card-body-categ">
        <h5 class="card-title"><%= @category.name %></h5>
        <div class="new-task">
          <i class="edit-icon bi-plus-square"></i>
          <%= link_to 'Add New Task', new_category_task_path(@category), class:"edit-icon" %> 
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <% @category.tasks.each do |task| %>
    <div class="col-sm-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= task.title %></h5>
          <br/>
          <h6 class="card-subtitle mb-2 text-muted">
            <i class="icon-x bi-clock-fill"></i>
            <%= task.date.strftime('%b %e, %Y') %>
          </h6>

          <% if task.completed == true %>
            <h6 class="card-subtitle mb-2 text-muted">
              <i class="icon-x bi-check-lg"></i>
              Completed
            </h6>
          <% else %>
            <h6 class="card-subtitle mb-2 text-muted">
              <i class="icon-x bi-caret-right"></i>
              Not Yet Completed
            </h6>           
          <% end %>
          
          <div class="rud">
            <i class="show-icon bi-eye-fill"></i>
            <%= link_to 'Show', category_task_path(@category, task), class:"show-icon" %>

            <i class="edit-icon bi-pencil-square"></i>
            <%= link_to 'Edit', edit_category_task_path(@category, task), class:"edit-icon" %> 

            <i class="delete-icon bi-trash-fill"></i>
            <%= link_to 'Delete', category_task_path(@category, task), method: :delete, data: { confirm: 'Are you sure?' }, class:"delete-icon" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<%= image_tag "logo2.png", height: 60 %>
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <% if user_signed_in? %>
                    <li class="nav-item">
                        <%= link_to 'CATEGORY', categories_path, class:"nav-link" %>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link">|</a>
                    </li> 

                    <li class="nav-item">
                        <%= link_to 'ADD NEW CATEGORY', new_category_path, class:"nav-link" %>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link">|</a>
                    </li> 

                    <li class="nav-item">
                    <%= link_to 'TASK TODAY', tasks_path, class:"nav-link" %>
                    </li>
                <% end %>
            </ul>
            <div class="d-flex">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                   
                    <% if user_signed_in? %>
                        <li class="nav-item dropdown">
                            <a class="nav-link">
                                <i class="icon-x bi-person-circle"></i> 
                                Hi, <%= current_user.email %>
                            </a>
                            <div class="dropdown-content">
                                <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
                            </div>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link">|</a>
                        </li> 

                        <li class="nav-item">
                            <%= link_to ' SIGN OUT', destroy_user_session_path, method: :delete, class:"nav-link bi-box-arrow-right" %> 
                        </li>
                    <% else %>
                        <li class="nav-item">
                            <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %> 
                        </li>
                        <li class="nav-item">
                            <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
                        </li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
</nav>

app/views/home/index.html.erb
<body class="home_bg">   
    <div class="datetime">
        <h2 class="journal">
            <i class="bi bi-suit-heart-fill"></i>
            <i class="bi bi-suit-heart-fill"></i> 
            MY JOURNAL 
            <i class="bi bi-suit-heart-fill"></i>
            <i class="bi bi-suit-heart-fill"></i>
        </h2>
        <div id="current_date"></div>
        <br/>
        <%= link_to 'GET STARTED', new_user_session_path, class:"btn btn-start" %>
    <div>
</body>

<script>
    months = ["January","February","March","April","May","June","July","August","September","October","November","December"];
    days = ["Sun","Mon","Tues","Wed","Thurs","Fri","Sat"];

    d = new Date();
    
    day = days[d.getDay()];
    month = months[d.getMonth()];
    date = d.getDate();
    year = d.getFullYear();

    hours = d.getHours();
    minutes = d.getMinutes();

    newformat = hours >= 12 ? 'PM' : 'AM';

    hours = hours % 12;

    hours = hours ? hours : 12; 
    hours = hours < 10 ? '0' + hours : hours;
    minutes = minutes < 10 ? '0' + minutes : minutes;

    document.getElementById("current_date").innerHTML = day + ' ' + month + ' ' + date + ', ' + year + ' ' + hours + ':' + minutes + ' ' + newformat;
</script>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">

    <title>My Journal App</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
    <% if user_signed_in? %>
      <%= render 'home/header' %>
    <% end %>
    <div class="container">
      <br/>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>

      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: [category, task]) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :notes %>
    <%= form.text_area :notes, class:"form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :date %>
    <%= form.date_select :date, class:"form-select" %>
  </div>

  <div class="form-check">
    <%= form.label :completed, class:"form-check-label" %>
    <%= form.check_box :completed, class:"form-check-input" %> 
  </div>

  <div class="actions center">
    <%= form.submit class:"btn btn-update" %>
    <%= link_to 'Back', category_path(@category), class:"btn btn-cancel" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="card">
    <div class="card-body margin">
        <h1 class="center">Editing Task</h1>
        <br/>
        <%= render 'form', category: @category, task: @task %>
        <br/>
    </div>
</div>
        

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks Due Today</h1>

<div class="row">
  <% @due.each do |task| %>
    <div class="col-sm-13">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= task.title %></h5>
          <br/>
          
          <h6 class="card-subtitle mb-2 text-muted">
            <i class="icon-x bi-journal-check"></i>
            <%= task.category.name %>
          </h6>

          <h6 class="card-subtitle mb-2 text-muted">
            <i class="icon-x bi-clock-fill"></i>
            <%= task.date.strftime('%b %e, %Y') %>
          </h6>
          
          <% if task.completed == true %>
            <h6 class="card-subtitle mb-2 text-muted">
              <i class="icon-x bi-check-lg"></i>
              Completed
            </h6>
          <% else %>
            <h6 class="card-subtitle mb-2 text-muted">
              <i class="icon-x bi-caret-right"></i>
              Not Yet Completed
            </h6>           
          <% end %>

          <div class="rud">
            <i class="show-icon bi-eye-fill"></i>
            <%= link_to 'Show', category_task_path(task.category_id, task), class:"show-icon" %>

            <i class="edit-icon bi-pencil-square"></i>
            <%= link_to 'Edit', edit_category_task_path(task.category_id, task), class:"edit-icon" %> 

            <i class="delete-icon bi-trash-fill"></i>
            <%= link_to 'Delete', category_task_path(task.category_id, task), method: :delete, data: { confirm: 'Are you sure?' }, class:"delete-icon" %>
          </div>
        </div
      </div>      
    </div>
  <% end %>
</div>

app/views/tasks/new.html.erb
<div class="card">
    <div class="card-body margin">
        <h1 class="center">New Task</h1>
        <br/>
        <%= render 'form', category: @category, task: @task %>
        <br/>
    </div>
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<div class="task-box">
  <div class="card-task">
      <div class="card-body margin2">
        <br/>
        <p class="myFont">
          <strong class="myFont">Title:</strong>
          <%= @task.title %>
        </p>

        <p class="myFont">
          <strong class="myFont">Notes:</strong>
          <%= @task.notes %>
        </p>

        <p class="myFont">
          <strong class="myFont">Due Date:</strong>
          <%= @task.date %>
        </p>

        <% if @task.completed == true %>
          <p class="myFont">
            <strong class="myFont">
              <i class="show-icon bi-check-circle-fill"></i>
              Completed
            </strong>
          </p>
        <% end %>

        <div class="rud2">
          <%= link_to ' Edit', edit_category_task_path(@category), class:"edit-icon bi-gear-fill" %> |
          <%= link_to ' Back', category_path(@category), class:"delete-icon bi-arrow-left-circle-fill" %>
          <br/>
        </div>
      </div>
  </div>
</div>